import os
import streamlit as st
from datetime import datetime
import json

def send_health_alert(alert_data):
    """
    Send email alert to health authorities about water quality issues.
    Integrates with SendGrid when configured, otherwise logs the alert.
    
    Args:
        alert_data: Dictionary containing alert information
    """
    
    # Check if SendGrid is configured via environment variables
    sendgrid_api_key = os.environ.get('SENDGRID_API_KEY')
    recipient_email = os.environ.get('HEALTH_AUTHORITY_EMAIL', 'health@example.com')
    
    # Prepare email content
    subject = f"🚨 URGENT: Water Quality Alert - {alert_data.get('severity', 'HIGH')} Risk Detected"
    
    email_body = f"""
    <html>
    <body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333;">
        <div style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); padding: 20px; border-radius: 10px;">
            <h1 style="color: white; margin: 0;">IBM Z Water Quality Alert System</h1>
        </div>
        
        <div style="padding: 20px; background-color: #f8f9fa; margin-top: 20px; border-radius: 5px;">
            <h2 style="color: #667eea;">⚠️ Alert Details</h2>
            <p><strong>Alert Type:</strong> {alert_data.get('type', 'Water Quality Warning')}</p>
            <p><strong>Severity Level:</strong> <span style="color: #dc3545; font-weight: bold;">{alert_data.get('severity', 'HIGH')}</span></p>
            <p><strong>Location:</strong> {alert_data.get('location', 'Multiple Water Sources')}</p>
            <p><strong>Timestamp:</strong> {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
        </div>
        
        <div style="padding: 20px; background-color: #fff3cd; margin-top: 20px; border-radius: 5px; border-left: 4px solid #ffc107;">
            <h3 style="color: #856404;">📊 Water Quality Metrics</h3>
            <ul>
                <li><strong>pH Level:</strong> {alert_data.get('ph', 'N/A')}</li>
                <li><strong>Turbidity:</strong> {alert_data.get('turbidity', 'N/A')} NTU</li>
                <li><strong>TDS:</strong> {alert_data.get('tds', 'N/A')} ppm</li>
                <li><strong>Dissolved Oxygen:</strong> {alert_data.get('dissolved_oxygen', 'N/A')} mg/L</li>
                <li><strong>Contamination Risk:</strong> {alert_data.get('contamination_risk', 'N/A')}%</li>
            </ul>
        </div>
        
        <div style="padding: 20px; background-color: #f8d7da; margin-top: 20px; border-radius: 5px; border-left: 4px solid #dc3545;">
            <h3 style="color: #721c24;">🏥 Health Impact Assessment</h3>
            <p><strong>Predicted Disease Risk:</strong> {alert_data.get('disease_risk', 'Unknown')}</p>
            <p><strong>Affected Population:</strong> {alert_data.get('affected_population', 'Estimated thousands')}</p>
            <p><strong>Recommended Action:</strong> {alert_data.get('recommended_action', 'Immediate water testing and public notification required')}</p>
        </div>
        
        <div style="padding: 20px; margin-top: 20px;">
            <p style="color: #666; font-size: 14px;">
                This alert was generated by the IBM Z Water Quality Prediction Dashboard.<br>
                For more details, please log into the dashboard at your earliest convenience.
            </p>
        </div>
    </body>
    </html>
    """
    
    # Try to send email using SendGrid if configured
    if sendgrid_api_key:
        try:
            # Import SendGrid library
            from sendgrid import SendGridAPIClient
            from sendgrid.helpers.mail import Mail, Email, To, Content
            
            message = Mail(
                from_email=Email('alerts@waterquality.ibmz.com'),
                to_emails=To(recipient_email),
                subject=subject,
                html_content=Content("text/html", email_body)
            )
            
            sg = SendGridAPIClient(sendgrid_api_key)
            response = sg.send(message)
            
            if response.status_code == 202:
                st.success(f"✅ Email alert sent successfully to {recipient_email}")
                return True, "Email sent successfully"
            else:
                st.warning(f"⚠️ Email sent but received status code: {response.status_code}")
                return False, f"Status code: {response.status_code}"
                
        except ImportError:
            st.info("📧 SendGrid library not installed. Install with: pip install sendgrid")
            # Log the alert instead
            log_alert(alert_data, email_body)
            return False, "SendGrid library not available"
        except Exception as e:
            st.error(f"❌ Failed to send email: {str(e)}")
            # Log the alert as fallback
            log_alert(alert_data, email_body)
            return False, str(e)
    else:
        # SendGrid not configured - log the alert
        st.info("📧 Email service not configured. Alert logged to system.")
        st.info("To enable email alerts, connect SendGrid integration and set SENDGRID_API_KEY and HEALTH_AUTHORITY_EMAIL environment variables.")
        log_alert(alert_data, email_body)
        return False, "Email service not configured"

def log_alert(alert_data, email_body=None):
    """Log alert to file system when email is not available"""
    try:
        # Create alerts directory if it doesn't exist
        os.makedirs('alerts', exist_ok=True)
        
        timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
        filename = f'alerts/alert_{timestamp}.json'
        
        # Save alert data as JSON
        with open(filename, 'w') as f:
            json.dump({
                'timestamp': datetime.now().isoformat(),
                'alert_data': alert_data,
                'email_content': email_body
            }, f, indent=2)
        
        st.success(f"✅ Alert logged to {filename}")
        return True
    except Exception as e:
        st.error(f"Failed to log alert: {str(e)}")
        return False

def get_recent_alerts(limit=10):
    """Retrieve recent alerts from the log"""
    alerts = []
    
    if not os.path.exists('alerts'):
        return alerts
    
    try:
        alert_files = sorted([f for f in os.listdir('alerts') if f.endswith('.json')], reverse=True)
        
        for filename in alert_files[:limit]:
            with open(f'alerts/{filename}', 'r') as f:
                alerts.append(json.load(f))
        
        return alerts
    except Exception as e:
        st.error(f"Failed to retrieve alerts: {str(e)}")
        return []

def configure_email_settings():
    """Display configuration UI for email settings"""
    st.subheader("📧 Email Alert Configuration")
    
    with st.expander("Configure Email Settings", expanded=False):
        st.markdown("""
        To enable real-time email alerts to health authorities:
        
        1. **Set up SendGrid Integration** (Recommended):
           - Connect SendGrid integration from the Integrations panel
           - Your API key will be automatically configured
        
        2. **Or manually set environment variables**:
           - `SENDGRID_API_KEY`: Your SendGrid API key
           - `HEALTH_AUTHORITY_EMAIL`: Recipient email address
        
        3. **Alternative**: Use Resend or other email service by modifying `utils/email_alerts.py`
        """)
        
        # Show current configuration status
        if os.environ.get('SENDGRID_API_KEY'):
            st.success("✅ SendGrid API Key is configured")
        else:
            st.warning("⚠️ SendGrid API Key not found")
        
        recipient = os.environ.get('HEALTH_AUTHORITY_EMAIL', 'Not configured')
        st.info(f"📬 Alert recipient: {recipient}")
        
        # Test email button
        if st.button("Send Test Alert"):
            test_alert = {
                'type': 'Test Alert',
                'severity': 'LOW',
                'location': 'Test Location',
                'ph': '7.2',
                'turbidity': '2.5',
                'tds': '450',
                'dissolved_oxygen': '8.0',
                'contamination_risk': '15',
                'disease_risk': 'Low',
                'affected_population': 'Test Population',
                'recommended_action': 'This is a test alert - no action required'
            }
            send_health_alert(test_alert)
